# Generated by Django 4.1.7 on 2023-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcargas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=11)),
                ('genero', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=50)),
                ('Barrio', models.CharField(max_length=20)),
                ('discapacidad', models.BooleanField()),
            ],
        ),
    ]
