# Generated by Django 4.1.7 on 2023-04-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcargas', '0003_familias_rename_productos_proyect_programas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudas_econ',
            name='monto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personas',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], max_length=1),
        ),
    ]
