# Generated by Django 4.1.7 on 2023-04-01 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcargas', '0004_alter_ayudas_econ_monto_alter_personas_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='familias',
            name='apellido',
            field=models.CharField(default='no especificado', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='apellido',
            field=models.CharField(default='no especificado', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personas',
            name='nombre',
            field=models.CharField(default='no especificado', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyect',
            name='area',
            field=models.CharField(default='gral', max_length=20),
            preserve_default=False,
        ),
    ]
