# Generated by Django 4.1.7 on 2023-04-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcargas', '0005_familias_apellido_personas_apellido_personas_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='apellido',
            field=models.CharField(max_length=12),
        ),
    ]
