# Generated by Django 4.1.7 on 2023-04-17 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcargas', '0009_familias_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='personas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familias',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='familias_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
