# Generated by Django 4.1.7 on 2023-04-18 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcargas', '0010_personas_usuario_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudas_econ',
            name='motivo',
            field=models.CharField(blank=True, default='emergencia', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ayudas_econ',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='ayudas_economicas', to=settings.AUTH_USER_MODEL),
        ),
    ]
