# Generated by Django 4.1.7 on 2023-04-18 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcargas', '0011_ayudas_econ_motivo_ayudas_econ_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='programa_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ayudas_econ',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ayudas_econ',
            name='id_programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appcargas.proyect'),
        ),
    ]
