# Generated by Django 4.1.7 on 2023-04-20 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcargas', '0012_proyect_usuario_creador_alter_ayudas_econ_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_usada', models.IntegerField(default=0)),
                ('cantidad_deposito', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, default='emergencia', max_length=20, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.categoria')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.personas')),
                ('id_programa', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appcargas.proyect')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.producto')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='prestaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
