# Generated by Django 4.1.7 on 2023-04-20 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcargas', '0013_categoria_producto_prestaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traking_Prestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('lugar_entrega', models.CharField(blank=True, max_length=20, null=True)),
                ('id_prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.prestaciones')),
                ('usuario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='aprobacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_entrega', models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='entrega', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitud', models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='solicitud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
