# Generated by Django 4.1.7 on 2023-04-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcargas', '0014_traking_prestaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEntregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.prestaciones')),
            ],
        ),
    ]
