# Generated by Django 4.1.7 on 2023-04-20 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcargas', '0015_trackingentregas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingAyudas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud_ay', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion_ay', models.DateField(blank=True, null=True)),
                ('fecha_entrega_ay', models.DateField(blank=True, null=True)),
                ('lugar_entrega', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ayudas_econ',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('APROBADO', 'APROBADO'), ('ENTREGADO', 'ENTREGADO')], default='SOLICITADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='prestaciones',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('APROBADO', 'APROBADO'), ('ENTREGADO', 'ENTREGADO')], default='SOLICITADO', max_length=15),
        ),
        migrations.DeleteModel(
            name='TrackingEntregas',
        ),
        migrations.AddField(
            model_name='trackingayudas',
            name='ayuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcargas.ayudas_econ'),
        ),
        migrations.AddField(
            model_name='trackingayudas',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='usuario_aprobacion_ay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackingayudas',
            name='usuario_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='usuario_entrega_ay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackingayudas',
            name='usuario_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('usuario eliminado'), related_name='usuario_solicitud_ay', to=settings.AUTH_USER_MODEL),
        ),
    ]
